name: Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Cache virtual environment
      uses: actions/cache@v4
      with:
        path: venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-venv-
    - name: Install dependencies
      run: ./script/setup
    - name: Run lint
      run: ./script/lint