name: Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort pyright
        ./script/setup

    - name: Run lint
      run: |
        source venv/bin/activate
        black src/
        isort src/
        pyright