name: Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: ./script/setup
     - name: Run lint
       run: |
         source venv/bin/activate
         black src/ tests/
         isort src/ tests/
         pyright