name: Lint and Test

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: ./script/setup
    - name: Run lint
      run: ./script/lint
    - name: Run tests
      run: ./script/test